name: Set MusicSource as parameter
description: Configure MusicSource in app.json

inputs:
  platform:
    description: 'Platform to prebuild - android or ios'
    required: true

runs:
  using: composite
  steps:
    - name: Setup
      uses: ./.github/actions/setup
    - name: Prebuild native files
      run: npx expo prebuild -p $EXPO_PLATFORM --clean
      shell: bash
      env:
        EXPO_PLATFORM: ${{ inputs.platform }}