name: Build
on:
  workflow_dispatch:

jobs:
  build_ios:
    name: Build IOS App
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install sponge
        run: brew install sponge
      - name: Setup
        uses: ./.github/actions/prebuild
        with:
          platform: "ios"
      - name: Build Expo IPA
        run: |
          cd ios
          xcodebuild -scheme MusicSource -workspace MusicSource.xcworkspace -configuration release archive -archivePath MusicSource.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
          chmod a+x ../scripts/xcarchive_to_ipa.sh
          ../scripts/xcarchive_to_ipa.sh MusicSource.xcarchive
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: app-release.ipa
          path: ios/*.ipa


  build_android:
    name: Build  Android  App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install moreutils
        run: sudo apt-get install moreutils
      - name: Setup
        uses: ./.github/actions/prebuild
        with:
          platform: "android"
      - name: Build Expo Android
        run: |
          cd android
          ./gradlew assembleRelease -PreactNativeArchitectures=armeabi-v7a
          mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/app-release-unknown.apk
          ./gradlew assembleRelease -PreactNativeArchitectures=armeabi-v7a
          mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/app-release-armeabi-v7a.apk
          ./gradlew assembleRelease -PreactNativeArchitectures=arm64-v8a
          mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/app-release-arm64-v8a.apk
          ./gradlew assembleRelease -PreactNativeArchitectures=x86
          mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/app-release-x86.apk
          ./gradlew assembleRelease -PreactNativeArchitectures=x86_64
          mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/app-release-x86_64.apk
      

      - name: Upload APK (unknown)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unknown.apk
          path: android/app/build/outputs/apk/release/app-release-unknown.apk
          compression-level: 9

      - name: Upload APK (armeabi-v7a)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-armeabi-v7a.apk
          path: android/app/build/outputs/apk/release/app-release-armeabi-v7a.apk
          compression-level: 9

      - name: Upload APK (arm64-v8a)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-arm64-v8a.apk
          path: android/app/build/outputs/apk/release/app-release-arm64-v8a.apk
          compression-level: 9

      - name: Upload APK (x86)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-x86.apk
          path: android/app/build/outputs/apk/release/app-release-x86.apk
          compression-level: 9

      - name: Upload APK (x86_64)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-x86_64.apk
          path: android/app/build/outputs/apk/release/app-release-x86_64.apk
          compression-level: 9

